import Head from 'next/head';
import { useUser, useSupabaseClient } from '@supabase/auth-helpers-react';
import PostCard from './components/PostCard';
import { useState, useEffect } from 'react';

export default function Home() {
  const user = useUser();
  const supabaseClient = useSupabaseClient();
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    getPosts();
  }, []);

  const getPosts = async () => {
    try {
      const { data, error } = await supabaseClient
        .from('posts')
        .select('*')
        .order('inserted_at', { ascending: false })
        .limit('8');
      if (data != null) {
        setPosts(data);
      }
    } catch (error) {
      alert(error.message);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {!user ? (
          <h2>Cari Teman Olah Raga</h2>
        ) : (
          <h2>Hi, {user.email}! Cari Teman Olahraga</h2>
        )}
        {posts.map((post) => (
          <PostCard
            title={post.title}
            content={post.content}
            key={post.id}
            jenis={post.jenis_olahraga}
            partisipan={post.partisipan}
            email={post.user_email}
            timestamp={post.inserted_at}
          />
        ))}
      </main>
    </>
  );
}
